[package]
name = "zeenmr-python"
version = "0.1.0"
authors = ["Maximilian Sombke <sombkemaximilian@gmail.com>"]
edition = "2024"
rust-version = "1.85.0"
description = """
    Python bindings for the ZeeNMR Rust library crate.
"""
readme = "../README.md"
repository = "https://github.com/SombkeMaximilian/zeenmr"
license = "MIT"
keywords = [
    "bioinformatics",
    "metabolomics",
    "nmr",
    "deconvolution",
]
categories = [
    "science::bioinformatics",
    "mathematics",
    "data-structures",
]
publish = false

[lib]
name = "_zeenmr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module"] }

[lints]
workspace = true
