use crate::intensity_array::LaneGeometry;
use crate::intensity_array::iter::SplitAt;
use std::iter::FusedIterator;
use std::marker::PhantomData;

/// Iterator over the buffer offsets of a lane along one dimension.
#[derive(Clone, Debug)]
pub struct LaneOffsets {
    /// Geometry of the lane.
    geometry: LaneGeometry,
    /// Next lane offset from the front.
    front: usize,
    /// Next lane offset from the back.
    back: usize,
}

impl Iterator for LaneOffsets {
    type Item = usize;

    fn next(&mut self) -> Option<Self::Item> {
        if self.front < self.back {
            let curr = self.geometry.offset_of_unvalidated(self.front);
            self.front += 1;

            Some(curr)
        } else {
            None
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.back - self.front;

        (remaining, Some(remaining))
    }
}

impl DoubleEndedIterator for LaneOffsets {
    fn next_back(&mut self) -> Option<Self::Item> {
        if self.front < self.back {
            self.back -= 1;

            Some(self.geometry.offset_of_unvalidated(self.back))
        } else {
            None
        }
    }
}

impl ExactSizeIterator for LaneOffsets {}

impl FusedIterator for LaneOffsets {}

// SAFETY: setting left.back and right.front to `self.front + index` achieves
// the disjoint split required by `SplitAt`.
unsafe impl SplitAt for LaneOffsets {
    fn split_at(self, index: usize) -> (Self, Self) {
        let mid = self.front + index;
        let left = Self {
            geometry: self.geometry,
            front: self.front,
            back: mid,
        };
        let right = Self {
            geometry: self.geometry,
            front: mid,
            back: self.back,
        };

        (left, right)
    }
}

impl LaneOffsets {
    /// Creates an iterator over the offsets of a lane.
    pub fn new(geometry: LaneGeometry) -> Self {
        Self {
            geometry,
            front: 0,
            back: geometry.len(),
        }
    }

    /// Returns the stride of the iterator.
    pub fn stride(&self) -> usize {
        self.geometry.stride()
    }
}

/// Strided iterator over the elements of a buffer.
#[derive(Debug)]
pub struct LaneElemStrided<'s, T> {
    /// Base pointer of the storage.
    base: *const T,
    /// Offsets to visit.
    ///
    /// # Safety
    ///
    /// All offsets returned by this iterator must be within bounds of the
    /// allocation `base` points into.
    offsets: LaneOffsets,
    /// Lifetime marker for the reference.
    ///
    /// # Safety
    ///
    /// This allows the borrow checker to ensure the pointer is never dangling.
    lifetime: PhantomData<&'s T>,
}

impl<T> Clone for LaneElemStrided<'_, T> {
    fn clone(&self) -> Self {
        Self {
            base: self.base,
            offsets: self.offsets.clone(),
            lifetime: PhantomData,
        }
    }
}

// SAFETY: grants shared access to `T`, so it is Send when `T` is Sync.
unsafe impl<T> Send for LaneElemStrided<'_, T> where T: Sync {}

// SAFETY: grants shared access to `T`, so it is Sync when `T` is Sync.
unsafe impl<T> Sync for LaneElemStrided<'_, T> where T: Sync {}

impl<'s, T> Iterator for LaneElemStrided<'s, T> {
    type Item = &'s T;

    fn next(&mut self) -> Option<Self::Item> {
        let next = self.offsets.next()?;

        // SAFETY: offsets are all guaranteed to be within bounds by
        // construction of this type
        Some(unsafe { &*self.base.add(next) })
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.offsets.size_hint()
    }
}

impl<'s, T> DoubleEndedIterator for LaneElemStrided<'s, T> {
    fn next_back(&mut self) -> Option<Self::Item> {
        let next = self.offsets.next_back()?;

        // SAFETY: offsets are all guaranteed to be within bounds by
        // construction of this type
        Some(unsafe { &*self.base.add(next) })
    }
}

impl<'s, T> ExactSizeIterator for LaneElemStrided<'s, T> {}

impl<'s, T> FusedIterator for LaneElemStrided<'s, T> {}

impl<'s, T> LaneElemStrided<'s, T> {
    /// Creates a strided iterator over the elements of `base` according to
    /// `geometry`.
    ///
    /// Returns `None` if any offset generated by `geometry` is out of bounds
    /// or overflows.
    pub fn new(base: &'s [T], geometry: LaneGeometry) -> Option<Self> {
        geometry.fits_within(base.len()).then(|| {
            // SAFETY: `Geometry::fits_within` guarantees that every offset
            // it addresses is non-overflowing and within `len` and thereby
            // within bounds of `base`.
            unsafe { Self::from_raw(base.as_ptr(), geometry) }
        })
    }

    /// Creates a strided iterator over the elements addressed by `geometry`
    /// relative to `base`.
    ///
    /// # Safety
    ///
    /// Every offset `geometry` addresses must be a valid index into the
    /// allocation `base` points into, and those elements must be borrowed
    /// immutably for `'s`.
    pub(crate) unsafe fn from_raw(base: *const T, geometry: LaneGeometry) -> Self {
        Self {
            base,
            offsets: LaneOffsets::new(geometry),
            lifetime: PhantomData,
        }
    }

    /// Returns the stride of the iterator.
    pub fn stride(&self) -> usize {
        self.offsets.geometry.stride()
    }
}

// SAFETY: see `LaneOffsets`.
unsafe impl<T> SplitAt for LaneElemStrided<'_, T> {
    fn split_at(self, index: usize) -> (Self, Self) {
        let (left, right) = self.offsets.split_at(index);

        (
            Self {
                base: self.base,
                offsets: left,
                lifetime: PhantomData,
            },
            Self {
                base: self.base,
                offsets: right,
                lifetime: PhantomData,
            },
        )
    }
}

/// Strided iterator over mutable references of the elements of a buffer.
#[derive(Debug)]
pub struct LaneElemStridedMut<'s, T> {
    /// Base pointer of the storage.
    base: *mut T,
    /// Offsets to visit.
    ///
    /// # Safety
    ///
    /// All offsets returned by this iterator must be within bounds of the
    /// allocation `base` points into, and the geometry must be injective, so
    /// no offset is yielded twice.
    offsets: LaneOffsets,
    /// Lifetime marker for the mutable reference which is invariant in `T`.
    ///
    /// # Safety
    ///
    /// This allows the borrow checker to ensure the pointer is never dangling.
    lifetime: PhantomData<&'s mut T>,
}

// SAFETY: grants unique access to `T`, so it is Send when `T` is Send.
unsafe impl<T> Send for LaneElemStridedMut<'_, T> where T: Send {}

// SAFETY: grants unique access to `T`, so it is Sync when `T` is Sync.
unsafe impl<T> Sync for LaneElemStridedMut<'_, T> where T: Sync {}

impl<'s, T> Iterator for LaneElemStridedMut<'s, T> {
    type Item = &'s mut T;

    fn next(&mut self) -> Option<Self::Item> {
        let next = self.offsets.next()?;

        // SAFETY: the offset is in bounds by construction, and injectivity
        // guarantees it is never yielded twice, so the returned reference is
        // unique.
        Some(unsafe { &mut *self.base.add(next) })
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.offsets.size_hint()
    }
}

impl<'s, T> DoubleEndedIterator for LaneElemStridedMut<'s, T> {
    fn next_back(&mut self) -> Option<Self::Item> {
        let next = self.offsets.next_back()?;

        // SAFETY: the offset is in bounds by construction, and injectivity
        // guarantees it is never yielded twice, so the returned reference is
        // unique.
        Some(unsafe { &mut *self.base.add(next) })
    }
}

impl<'s, T> ExactSizeIterator for LaneElemStridedMut<'s, T> {}

impl<'s, T> FusedIterator for LaneElemStridedMut<'s, T> {}

// SAFETY: see `LaneOffsets`.
unsafe impl<T> SplitAt for LaneElemStridedMut<'_, T> {
    fn split_at(self, index: usize) -> (Self, Self) {
        let (left, right) = self.offsets.split_at(index);

        (
            Self {
                base: self.base,
                offsets: left,
                lifetime: PhantomData,
            },
            Self {
                base: self.base,
                offsets: right,
                lifetime: PhantomData,
            },
        )
    }
}

impl<'s, T> LaneElemStridedMut<'s, T> {
    /// Creates a strided iterator over mutable references of the elements of
    /// `base` according to `geometry`.
    ///
    /// Returns `None` if any offset generated by `geometry` is out of bounds or
    /// overflows, or if `geometry` is not injective.
    pub fn new(base: &'s mut [T], geometry: LaneGeometry) -> Option<Self> {
        if !geometry.is_injective() {
            return None;
        }

        geometry.fits_within(base.len()).then(|| {
            // SAFETY: `Geometry::fits_within` guarantees that every offset
            // it addresses is non-overflowing and within `len` and thereby
            // within bounds of `base`. `Geometry::is_injective` guarantees
            // that every offset addressed by it is unique.
            unsafe { Self::from_raw(base.as_mut_ptr(), geometry) }
        })
    }

    /// Creates a strided iterator over mutable references to the elements
    /// addressed by `geometry` relative to `base`.
    ///
    /// # Safety
    ///
    /// Every offset `geometry` addresses must be a valid index into the
    /// allocation `base` points into, those elements must be borrowed mutably
    /// for `'s`. No other live reference to them must exist, and `geometry`
    /// must be injective so no offset is yielded twice.
    pub(crate) unsafe fn from_raw(base: *mut T, geometry: LaneGeometry) -> Self {
        debug_assert!(geometry.is_injective());

        Self {
            base,
            offsets: LaneOffsets::new(geometry),
            lifetime: PhantomData,
        }
    }

    /// Returns the stride of the iterator.
    pub fn stride(&self) -> usize {
        self.offsets.geometry.stride()
    }
}
