[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT"

[dependencies]
criterion = "0.8.2"
num-traits = { workspace = true }
rayon = { workspace = true }
zeenmr = { workspace = true, features = ["rayon"] }

[lints]
workspace = true

[[bench]]
name = "deconvolute"
path = "deconvolute.rs"
harness = false
