[package]
name = "zeenmr-spectrum"
version = "0.1.0"
authors = ["Maximilian Sombke <sombkemaximilian@gmail.com>"]
edition = "2024"
rust-version = "1.85.0"
description = """
    Data structures for representing NMR spectra and their properties.
"""
readme = "README.md"
repository = "https://github.com/spang-lab/zeenmr"
license = "MIT"
keywords = [
    "bioinformatics",
    "metabolomics",
    "nmr",
    "spectrum",
]
categories = [
    "science::bioinformatics",
    "data-structures",
]

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]
float-cmp = { workspace = true }
static_assertions = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

[lints]
workspace = true
