use std::fmt::Display;
use std::path::PathBuf;
use std::{env, fs};

#[cfg(feature = "detect-cpu-features")]
use hwlocality::{
    Topology,
    object::{attributes::ObjectAttributes, types::ObjectType},
};

const KIB: usize = 1 << 10;
const DEFAULT_SHARING: usize = 2;
const DEFAULT_LINE: usize = 128;
const DEFAULT_L1D: usize = 32 * KIB;
const DEFAULT_L2: usize = 256 * KIB;

const ENV_LINE: &str = "ZEENMR_CACHE_LINE";
const ENV_L1D: &str = "ZEENMR_L1D";
const ENV_L1D_SHARING: &str = "ZEENMR_L1D_SHARING";
const ENV_L2: &str = "ZEENMR_L2";
const ENV_L2_SHARING: &str = "ZEENMR_L2_SHARING";
const OVERRIDES: [&str; 5] = [ENV_LINE, ENV_L1D, ENV_L1D_SHARING, ENV_L2, ENV_L2_SHARING];

#[derive(Copy, Clone, Debug)]
struct CacheTopology {
    line: usize,
    l1d: usize,
    l1d_per_thread: usize,
    l2: usize,
    l2_per_thread: usize,
    discovered: [bool; 5],
}

impl Default for CacheTopology {
    fn default() -> Self {
        Self {
            line: DEFAULT_LINE,
            l1d: DEFAULT_L1D,
            l1d_per_thread: DEFAULT_L1D / DEFAULT_SHARING,
            l2: DEFAULT_L2,
            l2_per_thread: DEFAULT_L2 / DEFAULT_SHARING,
            discovered: [false; 5],
        }
    }
}

impl Display for CacheTopology {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let CacheTopology {
            line,
            l1d,
            l1d_per_thread,
            l2,
            l2_per_thread,
            discovered,
        } = *self;
        let [
            line_d,
            l1d_d,
            l1d_per_thread_d,
            l2_d,
            l2_per_thread_d,
        ] = discovered.map(|d| if d {
            "// detected using hwloc"
        } else {
            "// using default"
        });

        write!(
            f,
            "// DO NOT MANUALLY EDIT: generated by build.rs\n\
            pub const CACHE_LINE: usize = {line}; {line_d}\n\
            pub const L1D: usize = {l1d}; {l1d_d}\n\
            pub const L1D_PER_THREAD: usize = {l1d_per_thread}; {l1d_per_thread_d}\n\
            pub const L2: usize = {l2}; {l2_d}\n\
            pub const L2_PER_THREAD: usize = {l2_per_thread}; {l2_per_thread_d}\n\
            "
        )
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    for over in OVERRIDES {
        println!("cargo:rerun-if-env-changed={over}");
    }

    let mut cache_topology = detect_dispatch().unwrap_or_default();
    apply_overrides(&mut cache_topology);
    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("cache.rs");
    fs::write(&dest, cache_topology.to_string()).unwrap();
}

fn detect_dispatch() -> Option<CacheTopology> {
    let host = env::var("HOST").unwrap_or_default();
    let target = env::var("TARGET").unwrap_or_default();

    if host != target {
        if zeenmr_env_val().iter().any(Option::is_none) {
            let overrides = OVERRIDES.join("/");
            println!("cargo:warning=cross-compiling ({host} -> {target})");
            println!("cargo:warning=set {overrides} if the target's architecture differs");
        }

        None
    } else {
        detect_topology()
    }
}

#[cfg(feature = "detect-cpu-features")]
fn detect_topology() -> Option<CacheTopology> {
    let arch_topology = Topology::new().expect("probing architecture topology should always work");
    let mut discovered = [true; 5];
    let mut l1d = 0;
    let mut l1d_per_thread = 0;
    let mut l2 = 0;
    let mut l2_per_thread = 0;

    let line = arch_topology
        .objects_with_type(ObjectType::PU)
        .filter_map(|pu| {
            pu.ancestors()
                .filter_map(|ancestor| {
                    if let Some(ObjectAttributes::Cache(cache)) = ancestor.attributes() {
                        cache.line_size().map(|l| l.get())
                    } else {
                        None
                    }
                })
                .max()
        })
        .max()
        .expect("probing CPU cache line size should always work");

    let stats = arch_topology
        .cpu_cache_stats()
        .expect("probing CPU cache sizes should always work");
    let mut smallest_caches = stats
        .smallest_data_cache_sizes()
        .iter()
        .map(|l| *l as usize);
    l1d = smallest_caches
        .next()
        .expect("one cache level must be present");
    (l2, discovered[2]) = smallest_caches
        .next()
        .map_or((DEFAULT_L2, false), |l| (l, true));
    let mut smallest_caches = stats
        .smallest_data_cache_sizes_per_thread()
        .iter()
        .map(|l| *l as usize);
    (l1d_per_thread, discovered[3]) = smallest_caches
        .next()
        .map_or((l1d / DEFAULT_SHARING, false), |l| (l, true));
    (l2_per_thread, discovered[4]) = smallest_caches
        .next()
        .map_or((l2 / DEFAULT_SHARING, false), |l| (l, true));

    Some(CacheTopology {
        line,
        l1d,
        l1d_per_thread,
        l2,
        l2_per_thread,
        discovered,
    })
}

#[cfg(not(feature = "detect-cpu-features"))]
fn detect_topology() -> Option<CacheTopology> {
    None
}

fn apply_overrides(topology: &mut CacheTopology) {
    let override_vals = OVERRIDES
        .iter()
        .zip(zeenmr_env_val().into_iter())
        .filter_map(|(name, value)| value.map(|value| (name, value)));
    for (name, value) in override_vals {
        match *name {
            ENV_LINE => {
                topology.line = value;
                topology.discovered[0] = false;
            }
            ENV_L1D => {
                topology.l1d = value;
                topology.discovered[1] = false;
            }
            ENV_L1D_SHARING => {
                topology.l1d_per_thread = topology.l1d / value;
                topology.discovered[2] = false;
            }
            ENV_L2 => {
                topology.l2 = value;
                topology.discovered[3] = false;
            }
            ENV_L2_SHARING => {
                topology.l2_per_thread = topology.l2 / value;
                topology.discovered[4] = false;
            }
            _ => unreachable!("unknown override (this is a bug in the library)"),
        }
    }
}

fn zeenmr_env_val() -> [Option<usize>; 5] {
    OVERRIDES.map(env_num)
}

fn env_num(var: &str) -> Option<usize> {
    match env::var(var) {
        Ok(s) => Some(
            s.trim()
                .parse::<usize>()
                .ok()
                .and_then(|val| if val == 0 { None } else { Some(val) })
                .unwrap_or_else(|| panic!("{var} must be a positive, non-zero integer, got {s}")),
        ),
        Err(_) => None,
    }
}
